FROM grafana/grafana:9.5.0
COPY provisioning/dashboards.yaml /etc/grafana/provisioning/dashboards/dashboards.yaml
COPY provisioning/dashboards/overal.json /etc/grafana/provisioning/dashboards/overal.json