apiVersion: 1

Datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://currency_influxdb:8086
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
    secureJsonData:
      token: ${INFLUX_TOKEN}
